GET HTTP://localhost:8080/api/enderecos

###
GET HTTP://localhost:8080/api/enderecos/1

###

POST HTTP://localhost:8080/api/enderecos
Content-Type: application/json

{
    "rua": "Alameda dos anjos",
    "cep": 25754330,
    "numero": 161,
    "cidade": "teresopolis",
    "estado": "Rio de Janeiro",
    "cliente": {
        "id": 3
    }
}

###

PUT HTTP://localhost:8080/api/enderecos/1
Content-Type: application/json

{
    "rua": "Rua judith Mauricio de Paula",
    "numero": 291,
    "cep": 25964220,
    "cidade": "teresopolis",
    "estado": "Rio de Janeiro",
    "cliente": {
        "id": 1
    }
}

###

DELETE HTTP://localhost:8080/api/enderecos/2





